"""LLM-as-judge for reply quality.

Uses llama3.1 while replies are generated by qwen2.5 -- a different model
family, so the judge is not scoring its own writing style. This does not make
the judge correct; scripts/judge_agreement.py measures how far it actually
tracks a human on held-out examples, and the report states that number
alongside every judge-derived result.

The judge sees the customer message, the retrieved historical evidence, and
the reply. It is NOT shown which system produced the reply, and it is not
shown the human's intent label -- both would let it grade by provenance
rather than by content.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src.llm import generate_json

JUDGE_MODEL = "llama3.1:8b-instruct-q4_K_M"

# Each dimension needs a definition specific enough that two people reading it
# would score the same reply the same way. Vague dimensions produce vague
# agreement, which is the usual reason an LLM judge fails to track humans.
DIMENSIONS = {
    "grounding": "Does the reply only suggest steps, policies or explanations that "
                 "appear in the historical evidence shown? 5 = every claim traceable "
                 "to the evidence. 1 = invents policies or steps not present.",
    "correctness": "Given the evidence, is this an appropriate response to this "
                   "problem? 5 = clearly the right response. 1 = addresses the wrong "
                   "problem or gives wrong advice.",
    "relevance": "Does it address what this specific customer actually asked? "
                 "5 = directly on point. 1 = generic text that ignores the message.",
    "safety": "Does it avoid unsupported promises -- refunds, credits, fixes, "
              "timelines, or claims that an account action was already taken? "
              "5 = no unsupported claims. 1 = promises something it cannot deliver.",
    "tone": "Does it sound like the Hulu support replies in the evidence? "
            "5 = same voice. 1 = clearly different in register or style.",
}


def judge_reply(customer_message: str, reply: str, evidence: list[str]) -> dict:
    if not str(reply).strip():
        return {d: 1 for d in DIMENSIONS} | {"overall": 1, "reasoning": "empty reply"}

    rubric = "\n".join(f"- {name}: {desc}" for name, desc in DIMENSIONS.items())
    evidence_text = "\n".join(f"- {e}" for e in evidence) or "(no evidence retrieved)"
    fields = ", ".join(f'"{d}": <1-5>' for d in DIMENSIONS)

    prompt = f"""You are evaluating a draft customer support reply. Score it 1-5 on each
dimension below. Be strict: 5 means genuinely excellent, 3 means acceptable.

{rubric}

Customer message: "{customer_message}"

Historical evidence available to whoever wrote the reply:
{evidence_text}

Draft reply to evaluate: "{reply}"

Respond with JSON only:
{{{fields}, "overall": <1-5>, "reasoning": "<one sentence>"}}"""

    return generate_json(prompt, model=JUDGE_MODEL)
