"""Blind human rating of replies, to measure agreement with the LLM judge.

The assignment asks for evidence of how far the judge tracks a human. That
evidence cannot be generated by a model without becoming circular, so this is
a human step -- but a deliberately small one.

Blinding: the rater sees the customer message and one reply. Which system
produced it, and what the judge scored it, are both hidden. Replies are
shuffled, and the three systems are sampled evenly so agreement is not
measured on one system's output alone.
"""

import sys
import termios
import tty
from pathlib import Path

import pandas as pd
from rich.console import Console
from rich.panel import Panel

ROOT = Path(__file__).resolve().parent.parent
PRED = ROOT / "reports" / "predictions.csv"
OUT = ROOT / "reports" / "human_ratings.csv"

N_TO_RATE = 21  # 7 per system, ~4 minutes
SEED = 3
SYSTEMS = ["agent", "trivial", "nearest"]

con = Console()

SCALE = """  [cyan]1[/cyan]  useless or harmful
  [cyan]2[/cyan]  poor - barely addresses it
  [cyan]3[/cyan]  acceptable - would not embarrass anyone
  [cyan]4[/cyan]  good - genuinely helpful
  [cyan]5[/cyan]  excellent - what a great agent would send"""


def getkey() -> str:
    if not sys.stdin.isatty():
        return (sys.stdin.readline().strip() or "3")[:1]
    fd = sys.stdin.fileno()
    old = termios.tcgetattr(fd)
    try:
        tty.setraw(fd)
        k = sys.stdin.read(1)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old)
    return "q" if k in ("\x03", "\x04") else k


def build_queue(df: pd.DataFrame) -> pd.DataFrame:
    per_system = max(1, N_TO_RATE // len(SYSTEMS))
    rows = []
    for source in SYSTEMS:
        reply_col, judge_col = f"{source}_reply", f"judge_{source}_overall"
        if reply_col not in df:
            continue
        sub = df[df[reply_col].notna()].sample(
            min(per_system, len(df)), random_state=SEED)
        for _, r in sub.iterrows():
            rows.append({"customer_msg": r["customer_msg"], "source": source,
                         "reply": r[reply_col], "judge_score": r.get(judge_col)})
    q = pd.DataFrame(rows).sample(frac=1, random_state=SEED).reset_index(drop=True)
    q["human_score"] = pd.NA
    return q


def main() -> None:
    if OUT.exists():
        q = pd.read_csv(OUT)
    else:
        q = build_queue(pd.read_csv(PRED))

    q["human_score"] = pd.to_numeric(q["human_score"], errors="coerce")
    todo = q.index[q["human_score"].isna()].tolist()
    if not todo:
        con.print("[green]all rated -- run `make agreement`[/green]")
        return

    for n, idx in enumerate(todo):
        row = q.loc[idx]
        while True:
            con.clear()
            con.print(f"[dim]{n + 1}/{len(todo)}[/dim]\n")
            con.print(Panel(str(row.customer_msg), title="customer wrote",
                            border_style="cyan"))
            con.print(Panel(str(row.reply), title="proposed reply",
                            border_style="yellow"))
            con.print(SCALE)
            con.print("\n[dim]q = save & quit[/dim]")
            k = getkey()
            if k == "q":
                q.to_csv(OUT, index=False)
                con.print(f"\n[green]saved -- {len(todo) - n} left[/green]")
                return
            if k in "12345":
                q.at[idx, "human_score"] = int(k)
                q.to_csv(OUT, index=False)
                break
    q.to_csv(OUT, index=False)
    con.print(f"\n[green]done -- {len(q)} rated. run `make agreement`[/green]")


if __name__ == "__main__":
    main()
